
SELECT [Entity GUID]
      ,[Entity Name]
      ,[Domicile City]
      ,[Domicile State Province]
      ,[Domicile Country]
      ,[Principal Operations Country]
      ,[User Description]
      ,[Stock Symbol]
      ,[Public/Private Status]
      ,[Industry - VEIC 10 Category]
      ,[Industry - VEIC 100 Category]
      ,[Industry - VEIC 1000 Category]
      ,[Industry - VEIC Code]
      ,[Industry - VEIC Name]
      ,[Industry - ICB Industry]
      ,[Industry - ICB Supersector]
      ,[Industry - ICB Sector]
      ,[Industry - ICB Subsector]
      ,[Industry - ICB Subsector Code]
FROM (SELECT [Entity GUID]
      ,[Entity Name]
      ,[Domicile City]
      ,[Domicile State Province]
      ,[Domicile Country]
      ,[Principal Operations Country]
      ,[User Description]
      ,[Stock Symbol]
      ,[Public/Private Status]
      ,[Industry - VEIC 10 Category]
      ,[Industry - VEIC 100 Category]
      ,[Industry - VEIC 1000 Category]
      ,[Industry - VEIC Code]
      ,[Industry - VEIC Name]
      ,[Industry - ICB Industry]
      ,[Industry - ICB Supersector]
      ,[Industry - ICB Sector]
      ,[Industry - ICB Subsector]
      ,[Industry - ICB Subsector Code]
	  , ROW_NUMBER() OVER (PARTITION BY [Entity GUID] ORDER BY [Report Date Range] DESC) AS rn
  FROM [PRIVATE_MARKETS].[dbo].[company_report_data]
  WHERE [Entity GUID] IS NOT NULL) a
WHERE rn = 1