version: 2

models:
  - name: Portfolio
    description: ASI Net, Net funds.
    columns:
      - name: PortfolioID
        description: Primary key (assigned surrogate)
        tests:
          - unique
          - not_null
      - name: DisplayName
        description: Reporting name. The investment teams like to refer to portfolios by a specific name. 
      - name: ServiceProviderName
        description: The name of the portfolio in the data service (i.e. Burgiss)
        tests:
          - unique
          - not_null
      - name: LocalCurrencyCode
        description: The client currency, used for Fx conversions.
        tests:
          - not_null
          - accepted_values:
              values: ['USD', 'AUD', 'CAD', 'EUR', 'GBP', 'INR', 'JPY', 'KRW', 'NOK', 'SEK']
      - name: ShortName
        description: Shortened identifier for each portfolio
        tests:
          - unique
          - not_null
      - name: FundStrategy
        description: Shortname for each strategy (Venture etc.)
  - name: GPFund
    description: Net, general partner funds
    columns:
      - name: GPFundID
        description: Primary key (assigned surrogate)
        tests:
          - unique
          - not_null
      - name: DisplayName
        description: Reporting name. The investment teams like to refer to gp funds by a specific name instead of the manager name.
      - name: ServiceProviderName
        description: The name of the gp fund in the data service (i.e. Burgiss)
        tests:
          - not_null
      - name: OrgGUID
        description: A unique identifier generated by the service provider
        tests:
          - unique
          - not_null
      - name: LocalCurrencyCode
        description: The local currency, an input for Fx conversions.
        tests:
          - not_null
          - accepted_values:
              values: ['USD', 'AUD', 'CAD', 'EUR', 'GBP', 'INR', 'JPY', 'KRW', 'NOK', 'SEK']
      - name: FundSizeLocal
        description: The fund size in the respective local currency
        tests:
          - not_null
      - name: Exclude
        description: If a fund should be excluded from reporting
        tests:
          - accepted_values:
              values: [1, 0]
      - name: SideFund
        description: If it is a side fund
        tests:
          - accepted_values:
              values: [1, 0]
      - name: Geography
        description: The assigned region from the service provider
      - name: Industry
        description: The assigned industry from the service provider
      - name: ForeignBased
        description: Whether the GPFund is located outside the US.
  - name: Entity
    description: Gross holdings/companies
    columns:
      - name: EntityID
        description: Primary key (assigned surrogate)
        tests:
          - unique
          - not_null
      - name: EntityName
        description: Holdings/company name
      - name: PublicPrivateStatus
        description: Whether the company is privately or publicly held
        tests:
          - accepted_values:
              values: ['Public', 'Private']
      - name: IsInvestable
        description: Whether a holding/company can have investments. Determined by the VEICCode.
        tests:
          - not_null
          - accepted_values:
              values: [1, 0]