version: 2

models:
  - name: portfolios
    columns:
      -name:
       tests:
        - unique
        - not null
  - name: gpfunds
  - name: entities
    columns:
      -name: EntityGUID
       tests:
        - unique
        - not null